package com.payment.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

/**
 * Represents a payment associated with a booking.
 */
@Data
@Entity
public class Payment {

    /**
     * Unique identifier for the payment record.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)  // Automatically generate ID for the payment
    int generalPayId;

    /**
     * ID of the booking associated with this payment.
     */
    int bookingId;

    /**
     * Name of the user who made the payment.
     */
    String userName;

    /**
     * Unique payment identifier generated by the payment gateway.
     */
    String paymentId;

    /**
     * Indicates whether the booking has been confirmed (e.g., "Booked" or "Pending").
     */
    String isBooked;

    /**
     * Total payment amount for the booking.
     */
    Integer amount;
}