package com.payment.entities;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Represents the details of a transaction, including the payment ID, currency, amount, and key.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString  // Generates a toString() method to print the object in a human-readable form
public class TransactionDetails {

    /**
     * Unique payment identifier generated by Razorpay for the transaction.
     */
    private String paymentId;

    /**
     * Currency used for the transaction (e.g., INR).
     */
    private String currency;

    /**
     * The total amount for the transaction, typically in paise.
     */
    private Integer amount;

    /**
     * The API key used for interacting with the Razorpay client.
     */
    private String key;
}
